spring.application.name=SistemaMedico
spring.datasource.url=jdbc:postgresql://localhost:5432/hospitaldb
spring.datasource.username=postgres
spring.datasource.password=781253
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
# JWT
jwt.secret=c2VjcmV0S2V5UGFyYUpXVFRoaXNJc0F2ZXJ5TG9uZ1NlY3JldEtleUZvckpXVFRva2VuR2VuZXJhdGlvbjEyMzQ1Njc4OTA=
jwt.expiration=86400000
server.port=8081

# Configuración de Mailtrap para envío de correos
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=554583a99176b4
spring.mail.password=a274229093ba0f
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
